version: "3.8"

services:
  mongo:
    image: mongo:3.6.3
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=<%= appName %>
      - MONGO_INITDB_ROOT_PASSWORD=Hustonline87542701<%= appName %>
      - MONGO_INITDB_DATABASE=<%= appName %>
    container_name: <%= appName %>_mongo
    expose:
      - "27017"
    networks:
      - <%= appName %>
  redis:
    image: redis:4.0.8
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: <%= appName %>_redis
    volumes:
      - .data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    tty: true
    networks:
      - <%= appName %>
  app:
    image: registry.cn-hangzhou.aliyuncs.com/bingyan/go-web-container:3.0
    environment:
      - TZ=Asia/Shanghai
      - ENV=prod
    ports:
      - "3265:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/app
      - ./env:/env
      - ./log:/app/log
    depends_on:
      - mongo
      - redis
    container_name: <%= appName %>_app
    networks:
      - <%= appName %>
networks:
  <%= appName %>:
    driver: overlay
