version: "3.8"

services:
  mongo:
    image: mongo:3.6.3
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=
    container_name: blog_mongo
    expose:
      - "27017"
    networks:
      - blog
  redis:
    image: redis:6.2.5
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: blog_redis
    volumes:
      - .data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    tty: true
    networks:
      - blog
  app:
    image: blog
    environment:
      - TZ=Asia/Shanghai
      - ENV=
    ports:
      - "3265:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/src
      - ./env:/env
      - ./log:/log
    depends_on:
      - mongo
      - redis
    container_name: blog_app
    networks:
      - blog

networks:
  blog:
    driver: overlay
    attachable: true
