version: "3.8"

services:
  mongo:
    image: mongo:3.6.3
    volumes:
      - .data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    container_name: blog_mongo
    expose:
      - "27017"
    networks:
      - blog
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - blog
  redis:
    image: redis:6.2.5
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: blog_redis
    volumes:
      - .data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    tty: true
    networks:
      - blog
  app:
    image: build .
    environment:
      - TZ=Asia/Shanghai
      - ENV=dev
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./env:/env
      - ./log:/log
    depends_on:
      - mongo-express
      - redis
    container_name: blog_app
    networks:
      - blog

networks:
  blog:
    driver: overlay
    attachable: true
